CREATE TABLE registered_user (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE,
  hashed_pass TEXT NOT NULL
);

CREATE TABLE user_profile (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fk_user_id INTEGER REFERENCES registered_user(id) ON DELETE CASCADE NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  zip TEXT,
  profile_desc TEXT,
  profile_img_url TEXT
);

CREATE INDEX idx_user_zip
  ON user_profile(zip);

/* SKILLS TABLES */
CREATE TABLE category (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_name TEXT NOT NULL UNIQUE
);

CREATE TABLE skill (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fk_category_id INTEGER REFERENCES category(id) ON DELETE CASCADE NOT NULL,
  skill_name TEXT NOT NULL UNIQUE,
  skill_desc TEXT NOT NULL
);

CREATE INDEX idx_skill_category_id
  ON skill(fk_category_id);

CREATE TYPE skill_type AS ENUM ('PROVIDER', 'SEEKER');

CREATE TABLE link_user_skill ( 
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fk_user_id INTEGER REFERENCES registered_user(id) ON DELETE CASCADE NOT NULL,
  fk_skill_id INTEGER REFERENCES skill(id) ON DELETE CASCADE NOT NULL,
  user_skill_type skill_type,
  primary_img_url TEXT,
  primary_description TEXT 
  /*calc avg rating*/
);

CREATE INDEX idx_link_user_skill_user_id
  ON link_user_skill(fk_user_id);

CREATE INDEX idx_link_user_skill_skill_id
  ON link_user_skill(fk_skill_id);

CREATE TABLE skill_detail (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fk_link_user_skill_id INTEGER REFERENCES link_user_skill(id) ON DELETE CASCADE NOT NULL,
  detail_img_url TEXT,
  details_description TEXT
);

CREATE INDEX idx_skill_detail_link_user_skill_id
  ON skill_detail(fk_link_user_skill_id);

/* REVIEW TABLES */
CREATE TABLE review (
  fk_link_user_skill_id INTEGER REFERENCES link_user_skill(id) ON DELETE CASCADE NOT NULL,
  fk_user_id_review_provider INTEGER REFERENCES registered_user(id) ON DELETE CASCADE NOT NULL,
  rating INTEGER NOT NULL,
  review_text TEXT,
  PRIMARY KEY (fk_link_user_skill_id, fk_user_id_review_provider)
);

CREATE INDEX idx_review_link_user_skill_id
  ON review(fk_link_user_skill_id);

CREATE INDEX idx_review_user_id
  ON review(fk_user_id_review_provider);